/* This file is generated by the nymea build system. Any changes to this file will *
 * be lost. If you want to change this file, edit the plugin's json file.          *
 *                                                                                 *
 * NOTE: This file can be included only once per plugin. If you need to access     *
 * definitions from this file in multiple source files, use                        *
 * #include extern-plugininfo.h                                                    *
 * instead and re-run qmake.                                                       */

#ifndef PLUGININFO_H
#define PLUGININFO_H

#include "typeutils.h"

#include <QLoggingCategory>
#include <QObject>

extern "C" const QString libnymea_api_version() { return QString("7.3.0");}

Q_DECLARE_LOGGING_CATEGORY(dcDelta)
Q_LOGGING_CATEGORY(dcDelta, "Delta")

PluginId pluginId = PluginId("{d8931c3c-2e13-480c-84e2-b491c26538c7}");
VendorId nymeaVendorId = VendorId("{4f5d30f5-df94-4bd9-8c1b-12ebab9b2d62}");
ThingClassId deltainverterThingClassId = ThingClassId("{884a515c-1777-49b4-8934-7b6456f19100}");
ParamTypeId deltainverterThingSerialPortParamTypeId = ParamTypeId("{47126dce-2f1f-47d2-a0e6-2397353482bb}");
ParamTypeId deltainverterThingBaudrateParamTypeId = ParamTypeId("{18da1dd3-dba6-4ddf-897d-4ba0c1a6ef50}");
StateTypeId deltainverterConnectedStateTypeId = StateTypeId("{746967c4-ef56-4948-8cf5-32dfc0eab6eb}");
StateTypeId deltainverterCurrentPowerStateTypeId = StateTypeId("{3a879d9c-474c-4e4f-899b-30814ee2e0ba}");
StateTypeId deltainverterTotalEnergyProducedStateTypeId = StateTypeId("{70a7c868-fbdb-44a3-a706-96924c9c0ec7}");

const QString translations[] {
    //: The name of the ParamType (ThingClass: deltainverter, Type: thing, ID: {18da1dd3-dba6-4ddf-897d-4ba0c1a6ef50})
    QT_TRANSLATE_NOOP("Delta", "Baudrate"),

    //: The name of the StateType ({3a879d9c-474c-4e4f-899b-30814ee2e0ba}) of ThingClass deltainverter
    QT_TRANSLATE_NOOP("Delta", "CurrentPower"),

    //: The name of the ThingClass ({884a515c-1777-49b4-8934-7b6456f19100})
    QT_TRANSLATE_NOOP("Delta", "Deltainverter"),

    //: The name of the ParamType (ThingClass: deltainverter, Type: thing, ID: {47126dce-2f1f-47d2-a0e6-2397353482bb})
    QT_TRANSLATE_NOOP("Delta", "Serial port"),

    //: The name of the StateType ({70a7c868-fbdb-44a3-a706-96924c9c0ec7}) of ThingClass deltainverter
    QT_TRANSLATE_NOOP("Delta", "TotalEnergyProduced"),

    //: The name of the plugin Delta ({d8931c3c-2e13-480c-84e2-b491c26538c7})
    QT_TRANSLATE_NOOP("Delta", "delta"),

    //: The name of the vendor ({4f5d30f5-df94-4bd9-8c1b-12ebab9b2d62})
    QT_TRANSLATE_NOOP("Delta", "nymea"),

    //: The name of the StateType ({746967c4-ef56-4948-8cf5-32dfc0eab6eb}) of ThingClass deltainverter
    QT_TRANSLATE_NOOP("Delta", "reachable")
};

#endif // PLUGININFO_H
